//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoginData", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
    [System.SerializableAttribute()]
    public partial class LoginData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserData", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
    [System.SerializableAttribute()]
    public partial class UserData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Date_InField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string First_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string First_SurnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Second_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Second_SurnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int User_IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date_In {
            get {
                return this.Date_InField;
            }
            set {
                if ((this.Date_InField.Equals(value) != true)) {
                    this.Date_InField = value;
                    this.RaisePropertyChanged("Date_In");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string First_Name {
            get {
                return this.First_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.First_NameField, value) != true)) {
                    this.First_NameField = value;
                    this.RaisePropertyChanged("First_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string First_Surname {
            get {
                return this.First_SurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.First_SurnameField, value) != true)) {
                    this.First_SurnameField = value;
                    this.RaisePropertyChanged("First_Surname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Second_Name {
            get {
                return this.Second_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Second_NameField, value) != true)) {
                    this.Second_NameField = value;
                    this.RaisePropertyChanged("Second_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Second_Surname {
            get {
                return this.Second_SurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.Second_SurnameField, value) != true)) {
                    this.Second_SurnameField = value;
                    this.RaisePropertyChanged("Second_Surname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int User_Id {
            get {
                return this.User_IdField;
            }
            set {
                if ((this.User_IdField.Equals(value) != true)) {
                    this.User_IdField = value;
                    this.RaisePropertyChanged("User_Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tbl_roles", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
    [System.SerializableAttribute()]
    public partial class tbl_roles : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool activoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int rolesidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Project.ServiceReference.tbl_permisos[] tbl_permisosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Project.ServiceReference.tbl_usuarios[] tbl_usuariosField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                if ((this.activoField.Equals(value) != true)) {
                    this.activoField = value;
                    this.RaisePropertyChanged("activo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.descripcionField, value) != true)) {
                    this.descripcionField = value;
                    this.RaisePropertyChanged("descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int rolesid {
            get {
                return this.rolesidField;
            }
            set {
                if ((this.rolesidField.Equals(value) != true)) {
                    this.rolesidField = value;
                    this.RaisePropertyChanged("rolesid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Project.ServiceReference.tbl_permisos[] tbl_permisos {
            get {
                return this.tbl_permisosField;
            }
            set {
                if ((object.ReferenceEquals(this.tbl_permisosField, value) != true)) {
                    this.tbl_permisosField = value;
                    this.RaisePropertyChanged("tbl_permisos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Project.ServiceReference.tbl_usuarios[] tbl_usuarios {
            get {
                return this.tbl_usuariosField;
            }
            set {
                if ((object.ReferenceEquals(this.tbl_usuariosField, value) != true)) {
                    this.tbl_usuariosField = value;
                    this.RaisePropertyChanged("tbl_usuarios");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tbl_permisos", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
    [System.SerializableAttribute()]
    public partial class tbl_permisos : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool activoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int permisosidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Project.ServiceReference.tbl_roles[] tbl_rolesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                if ((this.activoField.Equals(value) != true)) {
                    this.activoField = value;
                    this.RaisePropertyChanged("activo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.descripcionField, value) != true)) {
                    this.descripcionField = value;
                    this.RaisePropertyChanged("descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int permisosid {
            get {
                return this.permisosidField;
            }
            set {
                if ((this.permisosidField.Equals(value) != true)) {
                    this.permisosidField = value;
                    this.RaisePropertyChanged("permisosid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Project.ServiceReference.tbl_roles[] tbl_roles {
            get {
                return this.tbl_rolesField;
            }
            set {
                if ((object.ReferenceEquals(this.tbl_rolesField, value) != true)) {
                    this.tbl_rolesField = value;
                    this.RaisePropertyChanged("tbl_roles");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tbl_usuarios", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
    [System.SerializableAttribute()]
    public partial class tbl_usuarios : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool activoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fecha_creacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fecha_ingresoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string primer_apellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string primer_nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string segundo_apellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string segundo_nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int talento_humanoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Project.ServiceReference.tbl_calendario[] tbl_calendarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Project.ServiceReference.tbl_calendario[] tbl_calendario1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Project.ServiceReference.tbl_departamento[] tbl_departamentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Project.ServiceReference.tbl_jerarquia[] tbl_jerarquiaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Project.ServiceReference.tbl_jerarquia[] tbl_jerarquia1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Project.ServiceReference.tbl_log_vacaciones[] tbl_log_vacacionesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Project.ServiceReference.tbl_roles[] tbl_rolesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Project.ServiceReference.tbl_vacaciones[] tbl_vacacionesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                if ((this.activoField.Equals(value) != true)) {
                    this.activoField = value;
                    this.RaisePropertyChanged("activo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fecha_creacion {
            get {
                return this.fecha_creacionField;
            }
            set {
                if ((this.fecha_creacionField.Equals(value) != true)) {
                    this.fecha_creacionField = value;
                    this.RaisePropertyChanged("fecha_creacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fecha_ingreso {
            get {
                return this.fecha_ingresoField;
            }
            set {
                if ((this.fecha_ingresoField.Equals(value) != true)) {
                    this.fecha_ingresoField = value;
                    this.RaisePropertyChanged("fecha_ingreso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string primer_apellido {
            get {
                return this.primer_apellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.primer_apellidoField, value) != true)) {
                    this.primer_apellidoField = value;
                    this.RaisePropertyChanged("primer_apellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string primer_nombre {
            get {
                return this.primer_nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.primer_nombreField, value) != true)) {
                    this.primer_nombreField = value;
                    this.RaisePropertyChanged("primer_nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string segundo_apellido {
            get {
                return this.segundo_apellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.segundo_apellidoField, value) != true)) {
                    this.segundo_apellidoField = value;
                    this.RaisePropertyChanged("segundo_apellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string segundo_nombre {
            get {
                return this.segundo_nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.segundo_nombreField, value) != true)) {
                    this.segundo_nombreField = value;
                    this.RaisePropertyChanged("segundo_nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int talento_humano {
            get {
                return this.talento_humanoField;
            }
            set {
                if ((this.talento_humanoField.Equals(value) != true)) {
                    this.talento_humanoField = value;
                    this.RaisePropertyChanged("talento_humano");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Project.ServiceReference.tbl_calendario[] tbl_calendario {
            get {
                return this.tbl_calendarioField;
            }
            set {
                if ((object.ReferenceEquals(this.tbl_calendarioField, value) != true)) {
                    this.tbl_calendarioField = value;
                    this.RaisePropertyChanged("tbl_calendario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Project.ServiceReference.tbl_calendario[] tbl_calendario1 {
            get {
                return this.tbl_calendario1Field;
            }
            set {
                if ((object.ReferenceEquals(this.tbl_calendario1Field, value) != true)) {
                    this.tbl_calendario1Field = value;
                    this.RaisePropertyChanged("tbl_calendario1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Project.ServiceReference.tbl_departamento[] tbl_departamento {
            get {
                return this.tbl_departamentoField;
            }
            set {
                if ((object.ReferenceEquals(this.tbl_departamentoField, value) != true)) {
                    this.tbl_departamentoField = value;
                    this.RaisePropertyChanged("tbl_departamento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Project.ServiceReference.tbl_jerarquia[] tbl_jerarquia {
            get {
                return this.tbl_jerarquiaField;
            }
            set {
                if ((object.ReferenceEquals(this.tbl_jerarquiaField, value) != true)) {
                    this.tbl_jerarquiaField = value;
                    this.RaisePropertyChanged("tbl_jerarquia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Project.ServiceReference.tbl_jerarquia[] tbl_jerarquia1 {
            get {
                return this.tbl_jerarquia1Field;
            }
            set {
                if ((object.ReferenceEquals(this.tbl_jerarquia1Field, value) != true)) {
                    this.tbl_jerarquia1Field = value;
                    this.RaisePropertyChanged("tbl_jerarquia1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Project.ServiceReference.tbl_log_vacaciones[] tbl_log_vacaciones {
            get {
                return this.tbl_log_vacacionesField;
            }
            set {
                if ((object.ReferenceEquals(this.tbl_log_vacacionesField, value) != true)) {
                    this.tbl_log_vacacionesField = value;
                    this.RaisePropertyChanged("tbl_log_vacaciones");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Project.ServiceReference.tbl_roles[] tbl_roles {
            get {
                return this.tbl_rolesField;
            }
            set {
                if ((object.ReferenceEquals(this.tbl_rolesField, value) != true)) {
                    this.tbl_rolesField = value;
                    this.RaisePropertyChanged("tbl_roles");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Project.ServiceReference.tbl_vacaciones[] tbl_vacaciones {
            get {
                return this.tbl_vacacionesField;
            }
            set {
                if ((object.ReferenceEquals(this.tbl_vacacionesField, value) != true)) {
                    this.tbl_vacacionesField = value;
                    this.RaisePropertyChanged("tbl_vacaciones");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tbl_calendario", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
    [System.SerializableAttribute()]
    public partial class tbl_calendario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int talento_humano_empleadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int talento_humano_jefeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Project.ServiceReference.tbl_tipo_dia tbl_tipo_diaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Project.ServiceReference.tbl_usuarios tbl_usuariosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Project.ServiceReference.tbl_usuarios tbl_usuarios1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int tipo_dia_idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fecha {
            get {
                return this.fechaField;
            }
            set {
                if ((this.fechaField.Equals(value) != true)) {
                    this.fechaField = value;
                    this.RaisePropertyChanged("fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int talento_humano_empleado {
            get {
                return this.talento_humano_empleadoField;
            }
            set {
                if ((this.talento_humano_empleadoField.Equals(value) != true)) {
                    this.talento_humano_empleadoField = value;
                    this.RaisePropertyChanged("talento_humano_empleado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int talento_humano_jefe {
            get {
                return this.talento_humano_jefeField;
            }
            set {
                if ((this.talento_humano_jefeField.Equals(value) != true)) {
                    this.talento_humano_jefeField = value;
                    this.RaisePropertyChanged("talento_humano_jefe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Project.ServiceReference.tbl_tipo_dia tbl_tipo_dia {
            get {
                return this.tbl_tipo_diaField;
            }
            set {
                if ((object.ReferenceEquals(this.tbl_tipo_diaField, value) != true)) {
                    this.tbl_tipo_diaField = value;
                    this.RaisePropertyChanged("tbl_tipo_dia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Project.ServiceReference.tbl_usuarios tbl_usuarios {
            get {
                return this.tbl_usuariosField;
            }
            set {
                if ((object.ReferenceEquals(this.tbl_usuariosField, value) != true)) {
                    this.tbl_usuariosField = value;
                    this.RaisePropertyChanged("tbl_usuarios");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Project.ServiceReference.tbl_usuarios tbl_usuarios1 {
            get {
                return this.tbl_usuarios1Field;
            }
            set {
                if ((object.ReferenceEquals(this.tbl_usuarios1Field, value) != true)) {
                    this.tbl_usuarios1Field = value;
                    this.RaisePropertyChanged("tbl_usuarios1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int tipo_dia_id {
            get {
                return this.tipo_dia_idField;
            }
            set {
                if ((this.tipo_dia_idField.Equals(value) != true)) {
                    this.tipo_dia_idField = value;
                    this.RaisePropertyChanged("tipo_dia_id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tbl_departamento", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
    [System.SerializableAttribute()]
    public partial class tbl_departamento : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool activoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int departamentoidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Project.ServiceReference.tbl_jerarquia[] tbl_jerarquiaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Project.ServiceReference.tbl_usuarios[] tbl_usuariosField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                if ((this.activoField.Equals(value) != true)) {
                    this.activoField = value;
                    this.RaisePropertyChanged("activo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int departamentoid {
            get {
                return this.departamentoidField;
            }
            set {
                if ((this.departamentoidField.Equals(value) != true)) {
                    this.departamentoidField = value;
                    this.RaisePropertyChanged("departamentoid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.descripcionField, value) != true)) {
                    this.descripcionField = value;
                    this.RaisePropertyChanged("descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Project.ServiceReference.tbl_jerarquia[] tbl_jerarquia {
            get {
                return this.tbl_jerarquiaField;
            }
            set {
                if ((object.ReferenceEquals(this.tbl_jerarquiaField, value) != true)) {
                    this.tbl_jerarquiaField = value;
                    this.RaisePropertyChanged("tbl_jerarquia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Project.ServiceReference.tbl_usuarios[] tbl_usuarios {
            get {
                return this.tbl_usuariosField;
            }
            set {
                if ((object.ReferenceEquals(this.tbl_usuariosField, value) != true)) {
                    this.tbl_usuariosField = value;
                    this.RaisePropertyChanged("tbl_usuarios");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tbl_jerarquia", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
    [System.SerializableAttribute()]
    public partial class tbl_jerarquia : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int departamentoidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int jefe_talentohumanoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int jerarquiaidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int talento_humanoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Project.ServiceReference.tbl_departamento tbl_departamentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Project.ServiceReference.tbl_usuarios tbl_usuariosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Project.ServiceReference.tbl_usuarios tbl_usuarios1Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int departamentoid {
            get {
                return this.departamentoidField;
            }
            set {
                if ((this.departamentoidField.Equals(value) != true)) {
                    this.departamentoidField = value;
                    this.RaisePropertyChanged("departamentoid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int jefe_talentohumano {
            get {
                return this.jefe_talentohumanoField;
            }
            set {
                if ((this.jefe_talentohumanoField.Equals(value) != true)) {
                    this.jefe_talentohumanoField = value;
                    this.RaisePropertyChanged("jefe_talentohumano");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int jerarquiaid {
            get {
                return this.jerarquiaidField;
            }
            set {
                if ((this.jerarquiaidField.Equals(value) != true)) {
                    this.jerarquiaidField = value;
                    this.RaisePropertyChanged("jerarquiaid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int talento_humano {
            get {
                return this.talento_humanoField;
            }
            set {
                if ((this.talento_humanoField.Equals(value) != true)) {
                    this.talento_humanoField = value;
                    this.RaisePropertyChanged("talento_humano");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Project.ServiceReference.tbl_departamento tbl_departamento {
            get {
                return this.tbl_departamentoField;
            }
            set {
                if ((object.ReferenceEquals(this.tbl_departamentoField, value) != true)) {
                    this.tbl_departamentoField = value;
                    this.RaisePropertyChanged("tbl_departamento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Project.ServiceReference.tbl_usuarios tbl_usuarios {
            get {
                return this.tbl_usuariosField;
            }
            set {
                if ((object.ReferenceEquals(this.tbl_usuariosField, value) != true)) {
                    this.tbl_usuariosField = value;
                    this.RaisePropertyChanged("tbl_usuarios");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Project.ServiceReference.tbl_usuarios tbl_usuarios1 {
            get {
                return this.tbl_usuarios1Field;
            }
            set {
                if ((object.ReferenceEquals(this.tbl_usuarios1Field, value) != true)) {
                    this.tbl_usuarios1Field = value;
                    this.RaisePropertyChanged("tbl_usuarios1");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tbl_log_vacaciones", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
    [System.SerializableAttribute()]
    public partial class tbl_log_vacaciones : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int estatus_actualField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> estatus_anteriorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fecha_modificacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int logidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Project.ServiceReference.tbl_estatus tbl_estatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Project.ServiceReference.tbl_estatus tbl_estatus1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Project.ServiceReference.tbl_usuarios tbl_usuariosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Project.ServiceReference.tbl_vacaciones tbl_vacacionesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int th_modificoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int vacacionesidField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int estatus_actual {
            get {
                return this.estatus_actualField;
            }
            set {
                if ((this.estatus_actualField.Equals(value) != true)) {
                    this.estatus_actualField = value;
                    this.RaisePropertyChanged("estatus_actual");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> estatus_anterior {
            get {
                return this.estatus_anteriorField;
            }
            set {
                if ((this.estatus_anteriorField.Equals(value) != true)) {
                    this.estatus_anteriorField = value;
                    this.RaisePropertyChanged("estatus_anterior");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fecha_modificacion {
            get {
                return this.fecha_modificacionField;
            }
            set {
                if ((this.fecha_modificacionField.Equals(value) != true)) {
                    this.fecha_modificacionField = value;
                    this.RaisePropertyChanged("fecha_modificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int logid {
            get {
                return this.logidField;
            }
            set {
                if ((this.logidField.Equals(value) != true)) {
                    this.logidField = value;
                    this.RaisePropertyChanged("logid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Project.ServiceReference.tbl_estatus tbl_estatus {
            get {
                return this.tbl_estatusField;
            }
            set {
                if ((object.ReferenceEquals(this.tbl_estatusField, value) != true)) {
                    this.tbl_estatusField = value;
                    this.RaisePropertyChanged("tbl_estatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Project.ServiceReference.tbl_estatus tbl_estatus1 {
            get {
                return this.tbl_estatus1Field;
            }
            set {
                if ((object.ReferenceEquals(this.tbl_estatus1Field, value) != true)) {
                    this.tbl_estatus1Field = value;
                    this.RaisePropertyChanged("tbl_estatus1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Project.ServiceReference.tbl_usuarios tbl_usuarios {
            get {
                return this.tbl_usuariosField;
            }
            set {
                if ((object.ReferenceEquals(this.tbl_usuariosField, value) != true)) {
                    this.tbl_usuariosField = value;
                    this.RaisePropertyChanged("tbl_usuarios");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Project.ServiceReference.tbl_vacaciones tbl_vacaciones {
            get {
                return this.tbl_vacacionesField;
            }
            set {
                if ((object.ReferenceEquals(this.tbl_vacacionesField, value) != true)) {
                    this.tbl_vacacionesField = value;
                    this.RaisePropertyChanged("tbl_vacaciones");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int th_modifico {
            get {
                return this.th_modificoField;
            }
            set {
                if ((this.th_modificoField.Equals(value) != true)) {
                    this.th_modificoField = value;
                    this.RaisePropertyChanged("th_modifico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int vacacionesid {
            get {
                return this.vacacionesidField;
            }
            set {
                if ((this.vacacionesidField.Equals(value) != true)) {
                    this.vacacionesidField = value;
                    this.RaisePropertyChanged("vacacionesid");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tbl_vacaciones", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
    [System.SerializableAttribute()]
    public partial class tbl_vacaciones : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int dias_solicitadosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int estatusidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fecha_de_aprobacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fecha_entradaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fecha_salidaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int fecha_solicitudField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int talento_humanoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Project.ServiceReference.tbl_estatus tbl_estatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Project.ServiceReference.tbl_log_vacaciones[] tbl_log_vacacionesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Project.ServiceReference.tbl_usuarios tbl_usuariosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int vacacionesidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int yearField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int dias_solicitados {
            get {
                return this.dias_solicitadosField;
            }
            set {
                if ((this.dias_solicitadosField.Equals(value) != true)) {
                    this.dias_solicitadosField = value;
                    this.RaisePropertyChanged("dias_solicitados");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int estatusid {
            get {
                return this.estatusidField;
            }
            set {
                if ((this.estatusidField.Equals(value) != true)) {
                    this.estatusidField = value;
                    this.RaisePropertyChanged("estatusid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fecha_de_aprobacion {
            get {
                return this.fecha_de_aprobacionField;
            }
            set {
                if ((this.fecha_de_aprobacionField.Equals(value) != true)) {
                    this.fecha_de_aprobacionField = value;
                    this.RaisePropertyChanged("fecha_de_aprobacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fecha_entrada {
            get {
                return this.fecha_entradaField;
            }
            set {
                if ((this.fecha_entradaField.Equals(value) != true)) {
                    this.fecha_entradaField = value;
                    this.RaisePropertyChanged("fecha_entrada");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fecha_salida {
            get {
                return this.fecha_salidaField;
            }
            set {
                if ((this.fecha_salidaField.Equals(value) != true)) {
                    this.fecha_salidaField = value;
                    this.RaisePropertyChanged("fecha_salida");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int fecha_solicitud {
            get {
                return this.fecha_solicitudField;
            }
            set {
                if ((this.fecha_solicitudField.Equals(value) != true)) {
                    this.fecha_solicitudField = value;
                    this.RaisePropertyChanged("fecha_solicitud");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int talento_humano {
            get {
                return this.talento_humanoField;
            }
            set {
                if ((this.talento_humanoField.Equals(value) != true)) {
                    this.talento_humanoField = value;
                    this.RaisePropertyChanged("talento_humano");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Project.ServiceReference.tbl_estatus tbl_estatus {
            get {
                return this.tbl_estatusField;
            }
            set {
                if ((object.ReferenceEquals(this.tbl_estatusField, value) != true)) {
                    this.tbl_estatusField = value;
                    this.RaisePropertyChanged("tbl_estatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Project.ServiceReference.tbl_log_vacaciones[] tbl_log_vacaciones {
            get {
                return this.tbl_log_vacacionesField;
            }
            set {
                if ((object.ReferenceEquals(this.tbl_log_vacacionesField, value) != true)) {
                    this.tbl_log_vacacionesField = value;
                    this.RaisePropertyChanged("tbl_log_vacaciones");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Project.ServiceReference.tbl_usuarios tbl_usuarios {
            get {
                return this.tbl_usuariosField;
            }
            set {
                if ((object.ReferenceEquals(this.tbl_usuariosField, value) != true)) {
                    this.tbl_usuariosField = value;
                    this.RaisePropertyChanged("tbl_usuarios");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int vacacionesid {
            get {
                return this.vacacionesidField;
            }
            set {
                if ((this.vacacionesidField.Equals(value) != true)) {
                    this.vacacionesidField = value;
                    this.RaisePropertyChanged("vacacionesid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int year {
            get {
                return this.yearField;
            }
            set {
                if ((this.yearField.Equals(value) != true)) {
                    this.yearField = value;
                    this.RaisePropertyChanged("year");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tbl_tipo_dia", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
    [System.SerializableAttribute()]
    public partial class tbl_tipo_dia : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int descripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Project.ServiceReference.tbl_calendario[] tbl_calendarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int tipo_dia_idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int descripcion {
            get {
                return this.descripcionField;
            }
            set {
                if ((this.descripcionField.Equals(value) != true)) {
                    this.descripcionField = value;
                    this.RaisePropertyChanged("descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Project.ServiceReference.tbl_calendario[] tbl_calendario {
            get {
                return this.tbl_calendarioField;
            }
            set {
                if ((object.ReferenceEquals(this.tbl_calendarioField, value) != true)) {
                    this.tbl_calendarioField = value;
                    this.RaisePropertyChanged("tbl_calendario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int tipo_dia_id {
            get {
                return this.tipo_dia_idField;
            }
            set {
                if ((this.tipo_dia_idField.Equals(value) != true)) {
                    this.tipo_dia_idField = value;
                    this.RaisePropertyChanged("tipo_dia_id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tbl_estatus", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
    [System.SerializableAttribute()]
    public partial class tbl_estatus : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool activoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int estatusidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Project.ServiceReference.tbl_log_vacaciones[] tbl_log_vacacionesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Project.ServiceReference.tbl_log_vacaciones[] tbl_log_vacaciones1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Project.ServiceReference.tbl_vacaciones[] tbl_vacacionesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                if ((this.activoField.Equals(value) != true)) {
                    this.activoField = value;
                    this.RaisePropertyChanged("activo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.descripcionField, value) != true)) {
                    this.descripcionField = value;
                    this.RaisePropertyChanged("descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int estatusid {
            get {
                return this.estatusidField;
            }
            set {
                if ((this.estatusidField.Equals(value) != true)) {
                    this.estatusidField = value;
                    this.RaisePropertyChanged("estatusid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Project.ServiceReference.tbl_log_vacaciones[] tbl_log_vacaciones {
            get {
                return this.tbl_log_vacacionesField;
            }
            set {
                if ((object.ReferenceEquals(this.tbl_log_vacacionesField, value) != true)) {
                    this.tbl_log_vacacionesField = value;
                    this.RaisePropertyChanged("tbl_log_vacaciones");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Project.ServiceReference.tbl_log_vacaciones[] tbl_log_vacaciones1 {
            get {
                return this.tbl_log_vacaciones1Field;
            }
            set {
                if ((object.ReferenceEquals(this.tbl_log_vacaciones1Field, value) != true)) {
                    this.tbl_log_vacaciones1Field = value;
                    this.RaisePropertyChanged("tbl_log_vacaciones1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Project.ServiceReference.tbl_vacaciones[] tbl_vacaciones {
            get {
                return this.tbl_vacacionesField;
            }
            set {
                if ((object.ReferenceEquals(this.tbl_vacacionesField, value) != true)) {
                    this.tbl_vacacionesField = value;
                    this.RaisePropertyChanged("tbl_vacaciones");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AuthenticateUser", ReplyAction="http://tempuri.org/IService1/AuthenticateUserResponse")]
        bool AuthenticateUser(Project.ServiceReference.LoginData LD);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AuthenticateUser", ReplyAction="http://tempuri.org/IService1/AuthenticateUserResponse")]
        System.Threading.Tasks.Task<bool> AuthenticateUserAsync(Project.ServiceReference.LoginData LD);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddEstatus_Descrption", ReplyAction="http://tempuri.org/IService1/AddEstatus_DescrptionResponse")]
        void AddEstatus_Descrption(string Desccription);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddEstatus_Descrption", ReplyAction="http://tempuri.org/IService1/AddEstatus_DescrptionResponse")]
        System.Threading.Tasks.Task AddEstatus_DescrptionAsync(string Desccription);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertRegistrationData", ReplyAction="http://tempuri.org/IService1/InsertRegistrationDataResponse")]
        bool InsertRegistrationData(Project.ServiceReference.UserData UD);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertRegistrationData", ReplyAction="http://tempuri.org/IService1/InsertRegistrationDataResponse")]
        System.Threading.Tasks.Task<bool> InsertRegistrationDataAsync(Project.ServiceReference.UserData UD);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetRolList", ReplyAction="http://tempuri.org/IService1/GetRolListResponse")]
        Project.ServiceReference.tbl_roles[] GetRolList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetRolList", ReplyAction="http://tempuri.org/IService1/GetRolListResponse")]
        System.Threading.Tasks.Task<Project.ServiceReference.tbl_roles[]> GetRolListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PostDepartmento", ReplyAction="http://tempuri.org/IService1/PostDepartmentoResponse")]
        void PostDepartmento(Project.ServiceReference.tbl_departamento departamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PostDepartmento", ReplyAction="http://tempuri.org/IService1/PostDepartmentoResponse")]
        System.Threading.Tasks.Task PostDepartmentoAsync(Project.ServiceReference.tbl_departamento departamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PostRol", ReplyAction="http://tempuri.org/IService1/PostRolResponse")]
        void PostRol(Project.ServiceReference.tbl_roles rol);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PostRol", ReplyAction="http://tempuri.org/IService1/PostRolResponse")]
        System.Threading.Tasks.Task PostRolAsync(Project.ServiceReference.tbl_roles rol);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUsuariosList", ReplyAction="http://tempuri.org/IService1/GetUsuariosListResponse")]
        Project.ServiceReference.tbl_usuarios[] GetUsuariosList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUsuariosList", ReplyAction="http://tempuri.org/IService1/GetUsuariosListResponse")]
        System.Threading.Tasks.Task<Project.ServiceReference.tbl_usuarios[]> GetUsuariosListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDepartamentosList", ReplyAction="http://tempuri.org/IService1/GetDepartamentosListResponse")]
        Project.ServiceReference.tbl_departamento[] GetDepartamentosList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDepartamentosList", ReplyAction="http://tempuri.org/IService1/GetDepartamentosListResponse")]
        System.Threading.Tasks.Task<Project.ServiceReference.tbl_departamento[]> GetDepartamentosListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetPermisosList", ReplyAction="http://tempuri.org/IService1/GetPermisosListResponse")]
        Project.ServiceReference.tbl_permisos[] GetPermisosList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetPermisosList", ReplyAction="http://tempuri.org/IService1/GetPermisosListResponse")]
        System.Threading.Tasks.Task<Project.ServiceReference.tbl_permisos[]> GetPermisosListAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Project.ServiceReference.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Project.ServiceReference.IService1>, Project.ServiceReference.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public bool AuthenticateUser(Project.ServiceReference.LoginData LD) {
            return base.Channel.AuthenticateUser(LD);
        }
        
        public System.Threading.Tasks.Task<bool> AuthenticateUserAsync(Project.ServiceReference.LoginData LD) {
            return base.Channel.AuthenticateUserAsync(LD);
        }
        
        public void AddEstatus_Descrption(string Desccription) {
            base.Channel.AddEstatus_Descrption(Desccription);
        }
        
        public System.Threading.Tasks.Task AddEstatus_DescrptionAsync(string Desccription) {
            return base.Channel.AddEstatus_DescrptionAsync(Desccription);
        }
        
        public bool InsertRegistrationData(Project.ServiceReference.UserData UD) {
            return base.Channel.InsertRegistrationData(UD);
        }
        
        public System.Threading.Tasks.Task<bool> InsertRegistrationDataAsync(Project.ServiceReference.UserData UD) {
            return base.Channel.InsertRegistrationDataAsync(UD);
        }
        
        public Project.ServiceReference.tbl_roles[] GetRolList() {
            return base.Channel.GetRolList();
        }
        
        public System.Threading.Tasks.Task<Project.ServiceReference.tbl_roles[]> GetRolListAsync() {
            return base.Channel.GetRolListAsync();
        }
        
        public void PostDepartmento(Project.ServiceReference.tbl_departamento departamento) {
            base.Channel.PostDepartmento(departamento);
        }
        
        public System.Threading.Tasks.Task PostDepartmentoAsync(Project.ServiceReference.tbl_departamento departamento) {
            return base.Channel.PostDepartmentoAsync(departamento);
        }
        
        public void PostRol(Project.ServiceReference.tbl_roles rol) {
            base.Channel.PostRol(rol);
        }
        
        public System.Threading.Tasks.Task PostRolAsync(Project.ServiceReference.tbl_roles rol) {
            return base.Channel.PostRolAsync(rol);
        }
        
        public Project.ServiceReference.tbl_usuarios[] GetUsuariosList() {
            return base.Channel.GetUsuariosList();
        }
        
        public System.Threading.Tasks.Task<Project.ServiceReference.tbl_usuarios[]> GetUsuariosListAsync() {
            return base.Channel.GetUsuariosListAsync();
        }
        
        public Project.ServiceReference.tbl_departamento[] GetDepartamentosList() {
            return base.Channel.GetDepartamentosList();
        }
        
        public System.Threading.Tasks.Task<Project.ServiceReference.tbl_departamento[]> GetDepartamentosListAsync() {
            return base.Channel.GetDepartamentosListAsync();
        }
        
        public Project.ServiceReference.tbl_permisos[] GetPermisosList() {
            return base.Channel.GetPermisosList();
        }
        
        public System.Threading.Tasks.Task<Project.ServiceReference.tbl_permisos[]> GetPermisosListAsync() {
            return base.Channel.GetPermisosListAsync();
        }
    }
}
